CRUD/CRUD/Models/Model.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;

namespace CRUD.Models
{
    public partial class Model : DbContext
    {
        public Model()
            : base("name=DBModel")
        {
        }

        public virtual DbSet<Personas> Personas { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Personas>()
                .Property(e => e.nombre)
                .IsUnicode(false);

            modelBuilder.Entity<Personas>()
                .Property(e => e.apellido)
                .IsUnicode(false);

            modelBuilder.Entity<Personas>()
                .Property(e => e.correo)
                .IsUnicode(false);
        }
    }
}

CRUD/CRUD/Models/Personas.cs
namespace CRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Personas
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int idPersonas { get; set; }

        [Required]
        public string nombre { get; set; }

        [Required]
        public string apellido { get; set; }

        [Required]
        public string correo { get; set; }
    }
}

CRUD/CRUD/Controllers/PersonaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using CRUD.Models;

namespace CRUD.Controllers
{
    public class PersonaController : Controller
    {
        // GET: Persona
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult listar() {

            List<Personas> oListarPersonas = new List<Personas>();
            using (Model db = new Model())
            {
                oListarPersonas = (from p in db.Personas select p).ToList();
            }

            return Json(new { data = oListarPersonas }, JsonRequestBehavior.AllowGet);
        }


        public JsonResult Obtener(int idPersonas) {
            Personas oPersonas = new Personas();
            using (Model db = new Model())
            {
                oPersonas = (from p in db.Personas
                             where p.idPersonas == idPersonas select p).FirstOrDefault();
            }

            return Json( oPersonas, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Guardar(Personas oPersona)
        {
            bool respuesta = true;
            try
            {
                if (oPersona.idPersonas == 0)
                {
                    using (Model db = new Model())
                    {
                        db.Personas.Add(oPersona);
                        db.SaveChanges();
                    }
                }
                else
                {
                    using (Model db = new Model())
                    {
                        Personas tempPersona = (from p in db.Personas
                                                where p.idPersonas == oPersona.idPersonas
                                                select p).FirstOrDefault();

                        tempPersona.nombre = oPersona.nombre;
                        tempPersona.apellido = oPersona.apellido;
                        tempPersona.correo = oPersona.correo;

                        db.SaveChanges();
                    }
                }
            }
            catch
            {
                respuesta = false;
            }

            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);

        }

        public JsonResult Eliminar(int idPersonas)
        {
            bool respuesta = true;
            try
            {
                using (Model db = new Model())
                {
                    Personas oPersona = new Personas();
                    oPersona = (from p in db.Personas.Where(x => x.idPersonas == idPersonas)
                                select p).FirstOrDefault();

                    db.Personas.Remove(oPersona);

                    db.SaveChanges();
                }
            }
            catch
            {
                respuesta = false;
            }

            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

    }
}

CRUD/CRUD/Views/Persona/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row m-4">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                EJEMPLO
            </div>

            <div class="card-body">
                <table id="tbPersona" class="table">
                    <thead>
                        <tr>
                            <td>Nombres</td>
                            <td>Apellidos</td>
                            <td>Correo</td>
                            <td></td>

                        </tr>

                    </thead>


                </table>
            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="FormModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Rol</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-12">
                        <!--input type="text" id="txtIdPersona" /-->
                        <div class="form-group">
                            <label for="txtNombre">Nombre:</label>
                            <input type="text" class="form-control" id="txtNombre">
                        </div>
                        <div class="form-group">
                            <label for="txtApellidos">Apellido:</label>
                            <input type="text" class="form-control" id="txtApellidos">
                        </div>
                        <div class="form-group">
                            <label for="txtCorreo">Correo:</label>
                            <input type="text" class="form-control" id="txtCorreo">
                        </div>


                    </div>
                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script>

        var tabla_persona;

        $(document).ready(function () {
            tabla_persona = $('#tbPersona').DataTable({
                "ajax": {
                    "url": "@Url.Action("listar", "Persona")",
                    "type": "GET",
                    "dataType": "json"
                },

                /*Aca armo las columnas y filas en el datatable*/
                "columns": [
                    { "data": "nombre" },
                    { "data": "apellido" },
                    { "data": "correo" },
                    { "data": "idPersonas", "render": function (data) {
                        return "<button class='btn btn-primary btn-sm' type='button' onclick='abrirModal(" + data + ")'><i class='fas fa-pen'></i></button>" +
                            "<button class='btn btn-danger btn-sm ml-2' type='button' onclick='Eliminar(" + data + ")'><i class='fa fa-trash'></i></button>"
                        },
                        "orderable": false,
                        "searchable": false,
                        "width": "150px"
                    }
                ],
                dom: 'Bfrtip',
                buttons: [
                    {
                        text: 'Agregar Nuevo',
                        attr: { class: 'btn btn-success btn-sm' },
                        action: function (e, dt, node, config) {
                            abrirModal(0)
                        }
                    }
                ]


            });
        });



        function abrirModal($idPersonas) {

            $("#txtIdPersona").val($idPersonas);
            if ($idPersonas != 0) {

                jQuery.ajax({
                    url: "@Url.Action("Obtener","Persona")" + "?idPersonas=" + $idPersonas,
                    type: "GET",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {

                       // console.log(data);

                        if (data != null) {

                            $("#txtNombre").val(data.nombre);
                            $("#txtApellidos").val(data.apellido);
                            $("#txtCorreo").val(data.correo);
                        }

                    }
                });
            } else {
                $("#txtNombre").val("");
                $("#txtApellidos").val("");
                $("#txtCorreo").val("");
            }

            $('#FormModal').modal('show');
        }

        function Guardar() {
            var $data = {
                oPersona: {
                    idPersonas: parseInt($("#txtIdPersona").val()),
                    nombre: $("#txtNombre").val(),
                    apellido: $("#txtApellidos").val(),
                    correo: $("#txtCorreo").val(),
                }


            }
            console.log($data);

           jQuery.ajax({
                url: "@Url.Action("Guardar", "Persona")",
                type: "POST",
                data: JSON.stringify($data),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    if (data.resultado) {
                        tabla_persona.ajax.reload();
                        $('#FormModal').modal('hide');
                    } else {
                        alert("No se pudo guardar los cambios");
                    }
                },
                error: function (error) {
                    console.log(error)
                },
                beforeSend: function () {

                }
           });
            console.log($data);
        }

        function Eliminar($idPersonas) {
            if (confirm("¿Realmente desea eliminar?")) {

                jQuery.ajax({
                    url: "@Url.Action("Eliminar", "Persona")" + "?idPersonas=" + $idPersonas,
                    type: "GET",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {

                        if (data.resultado) {
                            tabla_persona.ajax.reload();
                        }
                    }
                });


            }
        }

    </script>
}

CRUD/CRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Plugins/css")

    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="container-fluid">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Content/Plugins/js")
    @RenderSection("scripts", required: false)
</body>
</html>